server:
  port: 8008

open:
  meituan:
    order-status-notify-url: https://peisongopen.meituan.com/api/
    pre-create-order-url: https://peisongopen.meituan.com/api/order/preCreateByShop
    create-order-url: https://peisongopen.meituan.com/api/order/createByShop
    pre-cancel-order-url: https://peisongopen.meituan.com/api/
    cancel-order-url: https://peisongopen.meituan.com/api/
    order-detail-url: https://peisongopen.meituan.com/api/
    addtip-url: https://peisongopen.meituan.com/api/

swagger:
  urls: /swagger-ui.html,/swagger-resources,/v2/api-docs,/configuration,/webjars,/swagger-resources/configuration/ui,/swagger-resources/configuration/security