# https://cdn.mysql.com/archives/mysql-5.7/mysql-5.7.36-linux-glibc2.12-x86_64.tar.gz
# tar -zxvf mysql-5.7.36-linux-glibc2.12-x86_64.tar.gz
# mv mysql-5.7.36-linux-glibc2.12-x86_64 mysql
FROM centos:7
COPY mysql /