server:
  port: 8008

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/magic?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 12345678
    driver-class-name: com.mysql.jdbc.Driver