server:
  port: 8008

spring:
  redis:
    host: 192.168.221.129
    port: 6379
    database: 5
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 500
        min-idle: 0
    timeout: 1200