apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb-config-server-statefulset
  labels:
    app: "mongodb-config-server"
    release: "{{ .Release.Name }}"
spec:
  serviceName: "mongodb-config-server-service"
  replicas: {{ .Values.mongodb_config_server.replicas | default 1 }}
  selector:
    matchLabels:
      app: "mongodb-config-server"
      release: "{{ .Release.Name }}"
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: "mongodb-config-server"
        release: "{{ .Release.Name }}"
    spec:
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      restartPolicy: Always
      {{- if .Values.mongodb_config_server.affinity }}
      affinity:
      {{ tpl .Values.mongodb_config_server.affinity . | indent 8 }}
      {{- end }}
      containers:
      - name: mongodb-config-server
        image: "{{ .Values.image }}:{{ .Values.imageTag }}"
        imagePullPolicy: IfNotPresent
        command: ['/bin/bash', '-c', '/bin/bash /run.sh']
        livenessProbe:
          exec:
            command:
              - mongo
              - 127.0.0.1:{{ .Values.mongodb_config_server.port }}
              - --eval
              - "db.adminCommand('ping')"
          initialDelaySeconds: 30
          periodSeconds: 15
          timeoutSeconds: 60
          failureThreshold: 8
          successThreshold: 1
        volumeMounts:
          - name: ro
            mountPath: /etc/localtime:ro
          - name: data
            mountPath: /mongodb-config-server/data
          - name: mongodb-config-server-configmap
            mountPath: /run.sh
            subPath: run.sh
          - name: mongodb-config-server-configmap
            mountPath: /mongodb-config-server/conf/mongod.conf
            subPath: mongod.conf
      volumes:
        - name: ro
          hostPath:
            path: /etc/localtime
        - name: mongodb-config-server-configmap
          configMap:
            name: mongodb-config-server-configmap
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
      storageClassName: "local-path"