apiVersion: v1
kind: Service
metadata:
  name: mongodb-config-server-service
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: mongodb-config-server
      port: {{ .Values.mongodb_config_server.port }}
  selector:
    app: "mongodb-config-server"