apiVersion: batch/v1
kind: Job
metadata:
  name: redis-cluster
spec:
  template:
    spec:
      hostNetwork: false
      containers:
      - name: cluster
        image: "{{ .Values.image }}:{{ .Values.imageTag }}"
        command: ['/bin/bash', '-c', '/bin/bash /run.sh']
        volumeMounts:
          - name: redis-cluster-configmap
            mountPath: /run.sh
            subPath: run.sh
      volumes:
        - name: redis-cluster-configmap
          configMap:
            name: redis-cluster-configmap
      restartPolicy: OnFailure
