{{- if .Values.mysql_slave.enable }}
apiVersion: v1
kind: Service
metadata:
  name: mysql-slave-service
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: mysql-slave
      port: {{ .Values.mysql_slave.port }}
  selector:
    app: "mysql-ha"
{{- end }}