server:
  port: 8008

spring:
  activemq:
    broker-url: tcp://192.168.221.129:61616
  in-memory: false
  pool:
    enabled: true
    max-connections: 10
    idle-timeout: 30000
    expiry-timeout: 0
