apiVersion: v1
kind: Service
metadata:
  name: zookeeper-headless-service
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: zookeeper
      port: {{ .Values.zookeeper.port }}
    - name: zookeeper-tcp
      port: 2888
    - name: zookeeper-cluster
      port: 3888
  selector:
    app: "zookeeper"