{{- if .Values.elasticsearch_master.enable }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elasticsearch-master-statefulset
  labels:
    app: "elasticsearch"
    release: "{{ .Release.Name }}"
spec:
  serviceName: "elasticsearch-master-service"
  replicas: {{ .Values.elasticsearch_master.replicas | default 1 }}
  selector:
    matchLabels:
      app: "elasticsearch"
      release: "{{ .Release.Name }}"
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: "elasticsearch"
        release: "{{ .Release.Name }}"
    spec:
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      restartPolicy: Always
      {{- if .Values.elasticsearch_master.affinity }}
      affinity:
      {{ tpl .Values.elasticsearch_master.affinity . | indent 8 }}
      {{- end }}
      containers:
      - name: elasticsearch-master
        image: "{{ .Values.image }}:{{ .Values.imageTag }}"
        imagePullPolicy: IfNotPresent
        command: ['/bin/bash', '-c', '/bin/bash /run.sh']
        env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
        livenessProbe:
          tcpSocket:
            port: {{.Values.http_port}}
          initialDelaySeconds: 30
          periodSeconds: 15
          timeoutSeconds: 60
          failureThreshold: 8
          successThreshold: 1
        volumeMounts:
          - name: ro
            mountPath: /etc/localtime:ro
          - name: lib64
            mountPath: /usr/lib64
          - name: data
            mountPath: /elasticsearch/data
          - name: elasticsearch-master-configmap
            mountPath: /run.sh
            subPath: run.sh
          - name: elasticsearch-master-configmap
            mountPath: /elasticsearch/config/elasticsearch.yml
            subPath: elasticsearch.yml
      volumes:
        - name: ro
          hostPath:
            path: /etc/localtime
        - name: lib64
          hostPath:
            path: /usr/lib64
        - name: elasticsearch-master-configmap
          configMap:
            name: elasticsearch-master-configmap
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
      storageClassName: "local-path"
{{- end }}