/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_web_service_SearchJNI */

#ifndef _Included_com_web_service_SearchJNI
#define _Included_com_web_service_SearchJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_web_service_SearchJNI
 * Method:    searchByLinux
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_web_service_SearchJNI_searchByLinux
  (JNIEnv *, jclass);

/*
 * Class:     com_web_service_SearchJNI
 * Method:    searchByMac
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_web_service_SearchJNI_searchByMac
  (JNIEnv *, jclass);

/*
 * Class:     com_web_service_SearchJNI
 * Method:    searchByWindows
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_web_service_SearchJNI_searchByWindows
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
