apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-config-server-configmap
data:
  run.sh: |

    #!/bin/bash

    set -x

    echo "starting mongodb-config-server ..."
    mkdir -p /mongodb-config-server/logs
    mkdir -p /mongodb-config-server/pid
    mkdir -p /mongodb-config-server/conf
    rm -rf /mongodb-config-server/data/mongod.lock

    echo '1'
    sleep 10

    /mongodb/bin/mongod --port {{ .Values.mongodb_config_server.port }} --bind_ip 0.0.0.0 --configsvr --replSet config-server --dbpath /mongodb-config-server/data --pidfilepath /mongodb-config-server/pid/mongodb-config-server.pid --logpath /mongodb-config-server/logs/mongodb-config-server.log --config /mongodb-config-server/conf/mongod.conf &
    echo "started mongodb-config-server ..."
    tail -f /dev/null

  mongod.conf: |

    systemLog:
        logAppend: true
        logRotate: rename
        timeStampFormat: ctime
    storage:
        journal:
            enabled: false
            commitIntervalMs: 100
        syncPeriodSecs: 60
        engine: wiredTiger
        wiredTiger:
            engineConfig:
                cacheSizeGB: 1

