apiVersion: v1
kind: Service
metadata:
  name: {{.Values.servicename}}
spec:
  type: ClusterIP
  ports:
  - name: elasticsearch
    port: {{ .Values.http_port }}
    protocol: TCP
    targetPort: {{ .Values.http_port }}
  selector:
    app: "elasticsearch"