image: "redis"
imageTag: "5.0.9"

replicas: 3
servicename: redis-service
saslEnable: false
redis_master:
  port: 6379
  affinity: |
    #command
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchLabels:
              app: "redis-master"
          topologyKey: kubernetes.io/hostname

redis_slave:
  port: 6479
  affinity: |
    #command
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchLabels:
              app: "redis-slave"
          topologyKey: kubernetes.io/hostname
