apiVersion: v1
kind: Service
metadata:
  name: {{.Values.neo4j.servicename}}
spec:
  type: ClusterIP
  ports:
  - name: neo4j
    port: {{.Values.neo4j.port}}
    protocol: TCP
    targetPort: {{.Values.neo4j.port}}
  selector:
    app: "neo4j"