apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: neo4j-statefulset
  labels:
    app: "neo4j"
    release: "{{ .Release.Name }}"
spec:
  serviceName: "neo4j-headless-service"
  replicas: {{ .Values.neo4j.replicas | default 1 }}
  selector:
    matchLabels:
      app: "neo4j"
      release: "{{ .Release.Name }}"
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: "neo4j"
        release: "{{ .Release.Name }}"
    spec:
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      restartPolicy: Always
      {{- if .Values.neo4j.affinity }}
      affinity:
      {{ tpl .Values.neo4j.affinity . | indent 8 }}
      {{- end }}
      containers:
      - name: neo4j
        image: "{{ .Values.image }}:{{ .Values.imageTag }}"
        imagePullPolicy: IfNotPresent
        command: ['/bin/bash', '-c', '/bin/bash /run.sh']
        env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
        resources:
          requests:
            cpu: 100m
            memory: 1Gi
          limits:
            cpu: 4
            memory: 8Gi
        livenessProbe:
          tcpSocket:
            port: {{.Values.neo4j.port}}
          initialDelaySeconds: 120
          periodSeconds: 15
          timeoutSeconds: 60
          failureThreshold: 8
          successThreshold: 1
        volumeMounts:
          - name: ro
            mountPath: /etc/localtime:ro
          - name: data
            mountPath: /neo4j/data
          - name: neo4j-configmap
            mountPath: /run.sh
            subPath: run.sh
          - name: neo4j-configmap
            mountPath: /neo4j/conf/neo4j.conf.bak
            subPath: neo4j.conf.bak
      volumes:
        - name: ro
          hostPath:
            path: /etc/localtime
        - name: neo4j-configmap
          configMap:
            name: neo4j-configmap
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
      storageClassName: "local-path"