server:
  port: 8007

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/

spring:
  application:
    name: service1
  zipkin:
    base-url: http://192.168.221.129:9411/
    discoveryClientEnabled: false
  sleuth:
    sampler:
      probability: 1.0