{{- if .Values.mysql_slave.enable }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: mysql-ha-cronjob
spec:
  schedule: "*/10 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          dnsPolicy: ClusterFirstWithHostNet
          containers:
            - name: cataskrestart
              image: "{{ .Values.image }}:{{ .Values.imageTag }}"
              imagePullPolicy: IfNotPresent
              command:
                - /bin/sh
                - -c
                - echo '=='
              volumeMounts:
                - name: logs
                  mountPath: /root/scripts
                - name: mysql-ha-configmap
                  mountPath: /run.sh
                  subPath: run.sh
          volumes:
            - name: logs
              hostPath:
                path: /home/aicu-tob/logs/mysql-ha-cronjob
            - name: mysql-ha-configmap
              configMap:
                name: mysql-ha-configmap
          restartPolicy: OnFailure
{{- end }}