{{- if .Values.mysql_slave.enable }}
apiVersion: batch/v1
kind: Job
metadata:
  name: mysql-ha
spec:
  template:
    spec:
      hostNetwork: false
      containers:
      - name: cluster
        image: "{{ .Values.image }}:{{ .Values.imageTag }}"
        command: ['/bin/bash', '-c', '/bin/bash /run.sh']
        volumeMounts:
          - name: mysql-ha-configmap
            mountPath: /run.sh
            subPath: run.sh
      volumes:
        - name: mysql-ha-configmap
          configMap:
            name: mysql-ha-configmap
      restartPolicy: OnFailure
{{- end }}