image: "kafka"
imageTag: "2.12-1.1.1"

kafka:
  servicename: kafka-service
  zkservicename: zookeeper-service
  zkport: 8121
  saslEnable: false
  replicas: 1
  port: 8092
  affinity: |
    #command
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchLabels:
              app: "kafka"
          topologyKey: kubernetes.io/hostname
