server:
  port: 8008

spring:
  cloud:
    consul:
      host: 192.168.221.129
      port: 8500
#      token: acg-2021-ffmumu666
      discovery:
        service-name: ${spring.application.name}
#        acl-token: acg-2021-ffmumu666
        hostname: 192.168.221.129
  application:
    name: consul-producer
