apiVersion: v1
kind: Service
metadata:
  name: kafka-headless-service
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: kafka
      port: {{ .Values.kafka.port }}
  selector:
    app: "kafka"