apiVersion: v1
kind: Service
metadata:
  name: redis-slave-service
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: redis-slave
      port: {{ .Values.redis_slave.port }}
  selector:
    app: "redis-slave"