apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-slave-statefulset
  labels:
    app: "redis-slave"
    release: "{{ .Release.Name }}"
spec:
  serviceName: "redis-slave-service"
  replicas: {{ .Values.replicas | default 1 }}
  selector:
    matchLabels:
      app: "redis-slave"
      release: "{{ .Release.Name }}"
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: "redis-slave"
        release: "{{ .Release.Name }}"
    spec:
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      restartPolicy: Always
      {{- if .Values.redis_slave.affinity }}
      affinity:
      {{ tpl .Values.redis_slave.affinity . | indent 8 }}
      {{- end }}
      containers:
      - name: redis-slave
        image: "{{ .Values.image }}:{{ .Values.imageTag }}"
        imagePullPolicy: IfNotPresent
        command: ['/bin/bash', '-c', '/bin/bash /run.sh']
        env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
        livenessProbe:
          tcpSocket:
            port: {{.Values.redis_slave.port}}
          initialDelaySeconds: 30
          periodSeconds: 15
          timeoutSeconds: 60
          failureThreshold: 8
          successThreshold: 1
        volumeMounts:
          - name: ro
            mountPath: /etc/localtime:ro
          - name: data
            mountPath: /redis/data
          - name: redis-slave-configmap
            mountPath: /run.sh
            subPath: run.sh
          - name: redis-slave-configmap
            mountPath: /redis/redis.conf
            subPath: redis.conf
      volumes:
        - name: ro
          hostPath:
            path: /etc/localtime
        - name: redis-slave-configmap
          configMap:
            name: redis-slave-configmap
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
      storageClassName: "local-path"