apiVersion: v1
kind: Service
metadata:
  name: {{.Values.zookeeper.servicename}}
spec:
  type: ClusterIP
  ports:
  - name: zookeeper
    port: {{.Values.zookeeper.port}}
    protocol: TCP
    targetPort: {{.Values.zookeeper.port}}
  selector:
    app: "zookeeper"