server:
  port: 8008
  servlet:
    context-path: /
    session:
      timeout: 9000
spring:
  datasource:
    username: root
    password: 123
    url: jdbc:mysql://192.168.221.129:3306/a?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC&nullCatalogMeansCurrent=true
    driver-class-name: com.mysql.cj.jdbc.Driver
  activiti:
    history-level: full
    db-history-used: true
    check-process-definitions: false

logging:
  level:
    root: info
