server:
  port: 8007

grpc:
  server:
    port: 9099

spring:
  application:
    name: service1

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka/
