apiVersion: v1
kind: Service
metadata:
  name: consul-headless-service
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: consul
      port: {{ .Values.consul.port }}
  selector:
    app: "consul"