server:
  port: 8008

spring:
  datasource:
    url: jdbc:mysql://192.168.221.130:3306/magic?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 123
    driver-class-name: com.mysql.jdbc.Driver

magic-api:
  web: /magic
  resource:
    type: database
    tableName: magic_api
    prefix: /
    readonly: false
  sql-column-case: default
  page-config:
    size: size
    page: page
    default-page: 1
    default-size: 10
  response-code:
    success: 200
    invalid: 401
    exception: 500