image: "elasticsearch"
imageTag: "7.7.1"

servicename: elasticsearch-service

elasticsearch_master_data_ingest:
  enable: true
  port: 3306
  affinity: |
    #command
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchLabels:
              app: "mysql-ha"
          topologyKey: kubernetes.io/hostname

elasticsearch_master:
  enable: true
  port: 3306
  affinity: |
    #command
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchLabels:
              app: "mysql-ha"
          topologyKey: kubernetes.io/hostname

elasticsearch_data:
  enable: true
  port: 3306
  affinity: |
    #command
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchLabels:
              app: "mysql-ha"
          topologyKey: kubernetes.io/hostname

elasticsearch_ingest:
  enable: true
  port: 3306
  affinity: |
    #command
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchLabels:
              app: "mysql-ha"
          topologyKey: kubernetes.io/hostname
