image: "elasticsearch"
imageTag: "7.7.1"

servicename: elasticsearch-service

cluster_name: my-application
http_port: 9200
# 写⼊候选主节点的设备地址，在开启服务后可以被选为主节点
discovery_seed_hosts: ["master1", "master2", "master3"]
# 初始化⼀个新的集群时需要此配置来选举master
cluster_initial_master_nodes: ["elasticsearch-master-data-ingest-statefulset-0", "elasticsearch-master-data-ingest-statefulset-1", "elasticsearch-master-data-ingest-statefulset-2"]

elasticsearch_master_data_ingest:
  enable: true
  replicas: 3
  affinity: |
    #command
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchLabels:
              app: "elasticsearch"
          topologyKey: kubernetes.io/hostname

elasticsearch_master:
  enable: false
  replicas: 3
  affinity: |
    #command
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchLabels:
              app: "elasticsearch"
          topologyKey: kubernetes.io/hostname

elasticsearch_data:
  enable: false
  replicas: 3
  affinity: |
    #command
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchLabels:
              app: "elasticsearch"
          topologyKey: kubernetes.io/hostname

elasticsearch_ingest:
  enable: false
  replicas: 3
  affinity: |
    #command
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchLabels:
              app: "elasticsearch"
          topologyKey: kubernetes.io/hostname
