apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-mongos-configmap
data:
  run.sh: |

    #!/bin/bash

    set -x

    echo "starting mongodb-mongos ..."
    mkdir -p /mongodb-mongos/logs
    mkdir -p /mongodb-mongos/conf
    mkdir -p /mongodb-mongos/pid

    a=""
    for((i=0;i<{{ .Values.mongodb_config_server.replicas }};i++)); do
    echo '1'
    temp=mongodb-config-server-statefulset-$i.mongodb-config-server-service.default.svc.cluster.local:{{ .Values.mongodb_config_server.port }}
    while true
    do
    response=$(mongo $temp/admin --eval "db.adminCommand('ping')" | grep "ok")
    echo '2'
    if [[ $? -eq 0 ]]; then
      if [[ $response == *'"ok" : 1'* ]]; then
        break
      fi
    fi
    done
    if [ $i -ne 0 ]; then
      a=$a","$temp
    else
      a=$temp
    fi
    done

    cp /mongodb-mongos/conf/mongos-temp.conf /mongodb-mongos/conf/mongos.conf
    echo "configdb = config-server/$a" >> /mongodb-mongos/conf/mongos.conf

    echo '3'
    sleep 10

    mongos --port {{ .Values.mongodb_mongos.port }} --bind_ip 0.0.0.0 --pidfilepath /mongodb-mongos/pid/mongodb-mongos.pid --logpath /mongodb-mongos/logs/mongodb-mongos.log --config /mongodb-mongos/conf/mongos.conf &
    echo "started mongodb-mongos ..."
    tail -f /dev/null

  mongos-temp.conf: |

    maxConns = 1000
    logappend = true

