apiVersion: v1
kind: Service
metadata:
  name: mongodb-shard-master-service
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: mongodb-shard-master
      port: {{ .Values.mongodb_shard.port }}
  selector:
    app: "mongodb-shard-master"