{{- if .Values.mongodb_shard.slave.enable }}
apiVersion: v1
kind: Service
metadata:
  name: mongodb-shard-arbiter-service
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: mongodb-shard-arbiter
      port: {{ .Values.mongodb_shard.slave.arbiter.port }}
  selector:
    app: "mongodb-shard-arbiter"
{{- end }}