apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-shard-master-configmap
data:
  run.sh: |

    #!/bin/bash

    set -x

    echo "starting mongodb-shard-master ..."
    mkdir -p /mongodb-shard-master/conf
    mkdir -p /mongodb-shard-master/logs
    mkdir -p /mongodb-shard-master/pid
    rm -rf /mongodb-shard-master/data/mongod.lock
    /mongodb/bin/mongod --repair

    sleep 10

    echo '1'
    POD_NAME_TEMP='mongodb-shard-master-statefulset-'$(echo echo $POD_NAME | egrep -o "[0-9]+" | head -1)
    /mongodb/bin/mongod --port {{ .Values.mongodb_shard.port }} --bind_ip 0.0.0.0 --shardsvr --replSet $POD_NAME_TEMP --dbpath /mongodb-shard-master/data --pidfilepath /mongodb-shard-master/pid/mongodb-shard-master.pid --logpath /mongodb-shard-master/logs/mongodb-shard-master.log --config /mongodb-shard-master/conf/mongod.conf &
    echo "started mongodb-shard-master ..."
    tail -f /dev/null

  mongod.conf: |

    systemLog:
        logAppend: true
        logRotate: rename
        timeStampFormat: ctime
    storage:
        journal:
            enabled: false
            commitIntervalMs: 100
        syncPeriodSecs: 60
        engine: wiredTiger
        wiredTiger:
            engineConfig:
                cacheSizeGB: 16

