server:
  port: 8008

etcd:
  url: https://192.168.221.129:2379
  enable-ssl: true
  key: -----BEGIN CERTIFICATE-----
    MIID4TCCAsmgAwIBAgIJAPfEyXlryEwiMA0GCSqGSIb3DQEBCwUAMBIxEDAOBgNV
    BAMMB2V0Y2QtY2EwIBcNMjAxMTA1MDMyMTExWhgPMjEyMDEwMTIwMzIxMTFaMCox
    KDAmBgNVBAMMH2V0Y2QtbWVtYmVyLXlxMDEtYWlwLWdwdS10ZXN0MTUwggEiMA0G
    CSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQC71llFldMPfUguiYzWqIfhKoYxpL7X
    eDWsbpJgUCQZ42YEae2yQW+NKwjQv+IoxAVjz/cvTkBedI2IaknXZ4KbmKtoaBCP
    34vw+GCfuaIYTXQmMWdha7+wM0OPZTtmClYyxcsxqLRLr5X0aj+58MJEYRKbN6o4
    OgNoZfRgjQxeYugdnbIPMYeQOmio4qbojlafo/veAmHqEyfxAb6OHMOkl9UdnBud
    5tATR/dGWU6F90LrfNNhg7ASTlj6c9rIv0cw+/o04aA7zEU0MPub2dE0esLwG4R0
    4c0pfDs25XoXvHpv5igxGP/LhaDRjdur9d1VeC1173pYicMDWriaL5XBAgMBAAGj
    ggEeMIIBGjAdBgNVHSUEFjAUBggrBgEFBQcDAgYIKwYBBQUHAwEwCQYDVR0TBAIw
    ADAdBgNVHQ4EFgQU096+Zs00JrVOIGU+89aOShdvElcwHwYDVR0jBBgwFoAUt1YM
    +th0txrwKLSV4ddNjzh4wkAwga0GA1UdEQSBpTCBooIJbG9jYWxob3N0ghh5cTAx
    LWFpcC1ncHUtdGVzdDE1LnlxMDGCHWxiLWFwaXNlcnZlci5rdWJlcm5ldGVzLmxv
    Y2FsgiJldGNkLmt1YmUtc3lzdGVtLnN2Yy5jbHVzdGVyLmxvY2FsghRldGNkLmt1
    YmUtc3lzdGVtLnN2Y4IQZXRjZC5rdWJlLXN5c3RlbYIEZXRjZIcECplsEYcEfwAA
    ATANBgkqhkiG9w0BAQsFAAOCAQEAr54lQwoRECAZyfbD5CkGV4wpO0qgjMs+XWt2
    +qPggQ8q1oX2HtU3bo5qmnbXT+eTLtncEJxnIU92sCrFyZQJG+4MGPsde95GAq5D
    1b+ldmwwVIjw4epqWzlxdWDmtas/uQ1FwPaD7HhjNk2HjkfiI2lwS7thiUuImXAN
    e0NDgn8h+2oRBD676KUbqkEBXxaqc5KNZ66e2ezNK2P/bApulhXasnr9GKExNYR6
    T9T71Z9A4gvLsD3yZnEyGfIf3xCjqtApvBl++9US6AWG7WcU3qbLTgFP5TdNpEL1
    S8dI1hhIQK572U88Ph5IoT55CN2NOTNvfTnIaBspbLtKhMfUWg==
    -----END CERTIFICATE-----
  cert: -----BEGIN RSA PRIVATE KEY-----
    MIIEpQIBAAKCAQEAu9ZZRZXTD31ILomM1qiH4SqGMaS+13g1rG6SYFAkGeNmBGnt
    skFvjSsI0L/iKMQFY8/3L05AXnSNiGpJ12eCm5iraGgQj9+L8Phgn7miGE10JjFn
    YWu/sDNDj2U7ZgpWMsXLMai0S6+V9Go/ufDCRGESmzeqODoDaGX0YI0MXmLoHZ2y
    DzGHkDpoqOKm6I5Wn6P73gJh6hMn8QG+jhzDpJfVHZwbnebQE0f3RllOhfdC63zT
    YYOwEk5Y+nPayL9HMPv6NOGgO8xFNDD7m9nRNHrC8BuEdOHNKXw7NuV6F7x6b+Yo
    MRj/y4Wg0Y3bq/XdVXgtde96WInDA1q4mi+VwQIDAQABAoIBAQCrrZa8Rdq5Ln1Z
    o3ho/XHrt40dNIEEuKb96bW5d6X3T2J/qD2LDcmiEfIlsStIrRhsCLjYsMGeUxLE
    2riQuteh1ODdNTfl96CU5r6RXf4sDiaZfdAKN4vkxIX8Or8WXV45W5SC17mp71q0
    IKQME2PLUZnK6g6XA1b4BS9dS61BWb4I9mGwQYp19wuR7x+2D8xUjGZkoTO2yqC0
    n5zoMaKmAGAfxoryfF4/Jsp+wCzW5suzWqyhGd+ZmFFkYLqz/gEFKYh54z4UfMte
    hmhwzGPiXVLNQ3ew9UxSYqnEEISv4o6aXqlwMpjqxPJaAvEy2yFzUfqQBVGdqmUw
    xZKd6YndAoGBANwBlZz1aJup5bK8J4wM+UzTcssxSmEvnJP65K9DEKLovYD/YbSK
    /jAEPnHI2hCqw5ie06iSZC4fyeUccwa3T2ep7fvE+uf8L2+RY96dWXhS/U/jAicS
    /Zf5VhCMsxmJqlTzU0WdYtmRYHanhqBFQElcC7OAhbOmV0htPeiDJgpLAoGBANqR
    cylGX4DubpYqbxU+0JWU0R9epC3goa+waf3CIcV4qLraPbC/Hkjh8HK+JRYWcGg0
    HDLBUPzEfhbA/vtTIKPWjf5JJacHvslj1MN8XO5aAxRbZArJx86IAt0p7sdQX1SM
    +ciKjoe3c3p5dxqNnOL5hkPv4iEvxY9kDK+YABijAoGBALcITmtds+DFcQbJCHG4
    nXNv+vHXGRVPoglu0vCIb//Id1gpnySv+hcCgNzzB5CUMNP5VwfIerXw1mvYxk2R
    FeudcRNj5oY3xVMhdx/Oco/rIzliF/lgEEBuPE7ab2pQoLe6E843yPROwR0V9KfD
    1V7yx/1XcGRsf/MOh1G4Ql6PAoGBAKwC1igAmz7D5sJFiQCmW8+su9u9RuZYJ8c1
    xmSP+LYJXHkZMn28G2BueCZFYLh+Vl6bzClhnJQhK75KiyFN7Z0jSMJ73KcUYGDs
    MVDbueNXcZ7+wb//x0DSJ7bYvnOb3DqVbCsYaE2E4dvcZhC+rF6w06r5yfQmPYu4
    yIcUz9aTAoGAC3HqwFa2K+ExL1WywIHj7/pjN8+lW6w5vLv6VUjZxpH+/BEe306K
    otxncGdH5XzjReSMaWyNXEq1+h7maUCzUHDmu4jmXLMCyIsh0J8uELjg05WtUf6z
    5R7si44eSOmBQ9be3/y1yUdX7Hne3aTCWALK3lRjo/1w6WF+QpdgeCw=
    -----END RSA PRIVATE KEY-----