apiVersion: v1
kind: Service
metadata:
  name: {{.Values.servicename}}
spec:
  type: ClusterIP
  ports:
  - name: redis
    port: {{.Values.redis_master.port}}
    protocol: TCP
    targetPort: {{.Values.redis_master.port}}
  selector:
    app: "redis-master"