apiVersion: v1
kind: Service
metadata:
  name: redis-master-service
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: redis-master
      port: {{ .Values.redis_master.port }}
  selector:
    app: "redis-master"