server:
  port: 8008

open:
  ele:
    grant-type: authorization_code
    code: wuhp
    app-id: 2546054523670710057
    merchant-id: 5313827
    app-secret: 6326d067-fc17-4521-b578-833f2af3cbaf
    token-url: https://exam-anubis.ele.me/anubis-webapi/openapi/token
    order-status-notify-url: http://saaa.com
    pre-create-order-url: https://exam-anubis.ele.me/anubis-webapi/v3/invoke/preCreateOrder
    create-order-url: https://exam-anubis.ele.me/anubis-webapi/v3/invoke/createOrder
    pre-cancel-order-url: https://exam-anubis.ele.me/anubis-webapi/v3/invoke/preCancelOrder
    cancel-order-url: https://exam-anubis.ele.me/anubis-webapi/v3/invoke/cancelOrder
    order-detail-url: https://exam-anubis.ele.me/anubis-webapi/v3/invoke/getOrderDetail
    addtip-url: https://exam-anubis.ele.me/anubis-webapi/v3/invoke/addTip
    storequery-url: https://exam-anubis.ele.me/anubis-webapi/v3/invoke/chainstoreQuery
    storequerylist-url: https://exam-anubis.ele.me/anubis-webapi/v3/invoke/chainstoreQueryList
    storecreate-url: https://exam-anubis.ele.me/anubis-webapi/v3/invoke/chainstoreCreate

swagger:
  urls: /swagger-ui.html,/swagger-resources,/v2/api-docs,/configuration,/webjars,/swagger-resources/configuration/ui,/swagger-resources/configuration/security