apiVersion: v1
kind: Service
metadata:
  name: mysql-master-service
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: mysql-master
      port: {{ .Values.mysql_master.port }}
  selector:
    app: "mysql-ha"