apiVersion: v1
kind: Service
metadata:
  name: {{.Values.servicename}}
spec:
  type: ClusterIP
  ports:
  - name: mysql
    port: {{.Values.mysql_master.port}}
    protocol: TCP
    targetPort: {{.Values.mysql_master.port}}
  selector:
    app: "mysql-ha"