server:
  port: 8008

mybatis:
  mapper-locations: classpath:com/web/mapper/*.xml
  type-aliases-package: com.web.*.entity
  configuration:
    cache-enabled: true

db:
  default:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.221.129:3306/a?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123
  private:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.221.129:3306/b?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123
