apiVersion: v1
kind: Service
metadata:
  name: {{.Values.consul.servicename}}
spec:
  type: ClusterIP
  ports:
  - name: consul
    port: {{.Values.consul.port}}
    protocol: TCP
    targetPort: {{.Values.consul.port}}
  selector:
    app: "consul"