apiVersion: v1
kind: Service
metadata:
  name: {{.Values.kafka.servicename}}
spec:
  type: ClusterIP
  ports:
  - name: kafka
    port: {{.Values.kafka.port}}
    protocol: TCP
    targetPort: {{.Values.kafka.port}}
  selector:
    app: "kafka"