apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-master-configmap
data:
  run.sh: |

    #!/bin/bash

    set -x

    echo "starting mysql-master ..."
    mkdir -p /mysql/tmp
    mkdir -p /mysql/conf
    mkdir -p /mysql/data

    groupadd mysql
    useradd -r -g mysql mysql
    groups mysql
    # 必须执行
    chown -R mysql:mysql /mysql

    /mysql/bin/mysqld --defaults-file=/mysql/conf/my.cnf --user=mysql --basedir=/mysql --datadir=/mysql/data --initialize
    # initialize specified but the data directory has files in it

    nohup /mysql/bin/mysqld_safe --defaults-file=/mysql/conf/my.cnf &
    ln -s /mysql/tmp/mysql.sock /tmp/mysql.sock

    sleep 5

    response1=$(/mysql/bin/mysql -uroot -p'{{.Values.password}}')
    if [[ $? -ne 0 ]]; then
      p=`cat /mysql/data/mysql.err | grep password | awk -F'root@localhost: ' '{print $2}'`
      while true
      do
      sleep 1
      response2=$(/mysql/bin/mysqladmin -u root -p$p password "{{.Values.password}}")
      if [[ $? -eq 0 ]]; then
        while true
        do
        sleep 1
        response3=$(/mysql/bin/mysql -uroot -p'{{.Values.password}}' -e"update mysql.user set host='%' where user='root';flush privileges;")
        if [[ $? -eq 0 ]]; then
          break
        fi
        done
        break
      else
        response7=$(/mysql/bin/mysql -uroot -p'{{.Values.password}}' -e"show slave status \G;")
        echo $response7
        if [[ $response7 == *"Slave_IO_Running: No"* ]]; then
          if [[ $response7 == *"Slave_SQL_Running: No"* ]]; then
            break
          fi
        fi
      fi
      done
    fi

    echo "started mysql-master ..."
    tail -f /dev/null

  my.cnf: |

    [mysqld]
    log-bin=mysql-bin
    server-id=1
    bind-address=0.0.0.0
    port={{.Values.mysql_master.port}}
    basedir=/mysql
    datadir=/mysql/data
    socket=/mysql/tmp/mysql.sock
    log-error=/mysql/data/mysql.err
    pid-file=/mysql/data/mysql.pid
    binlog-ignore-db=mysql
    binlog_ignore_db=information_schema
    binlog_ignore_db=performation_schema
    binlog_ignore_db=sys
    binlog_format=MIXED

    character_set_server=utf8mb4
    symbolic-links=0
    explicit_defaults_for_timestamp=true

