# https://fastdl.mongodb.org/linux/mongodb-linux-x86_64-rhel70-3.6.23.tgz
# tar -zxvf mongodb-linux-x86_64-rhel70-3.6.23.tgz
# mv mongodb-linux-x86_64-rhel70-3.6.23 mongodb
FROM centos:7
COPY mongodb /mongodb