# https://fastdl.mongodb.org/linux/mongodb-shell-linux-x86_64-rhel70-4.4.17.tgz
# tar -zxvf mongodb-shell-linux-x86_64-rhel70-4.4.17.tgz
# mv mongodb-shell-linux-x86_64-rhel70-4.4.17 mongodb
FROM centos:7
COPY mongodb /