# https://fastdl.mongodb.org/linux/mongodb-shell-linux-x86_64-rhel70-3.6.23.tgz
# tar -zxvf mongodb-shell-linux-x86_64-rhel70-3.6.23.tgz
# mv mongodb-shell-linux-x86_64-rhel70-3.6.23 mongodb
FROM centos:7
COPY mongodb /mongodb