apiVersion: v1
kind: Service
metadata:
  name: {{.Values.mongodb_mongos.servicename}}
spec:
  type: ClusterIP
  ports:
  - name: mongodb-mongos
    port: {{.Values.mongodb_mongos.port}}
    protocol: TCP
    targetPort: {{.Values.mongodb_mongos.port}}
  selector:
    app: "mongodb-mongos"