server:
  port: 8008

spring:
  application:
    name: gateway-server

  cloud:
    # 网关配置
    gateway:
      # 路由配置：转发规则
      routes: #集合。
        # id: 唯一标识。默认是一个UUID
        # uri: 转发路径
        # predicates: 条件,用于请求网关路径的匹配规则
        # filters：配置局部过滤器的

        - id: hystrix-provider
          # 静态路由
          # uri: http://localhost:8001/
          # 动态路由
          uri: lb://hystrix-provider
          predicates:
            - Path=/goods/**
        #        filters:
        #        - AddRequestParameter=username,zhangsan

        - id: hystrix-consumer
          # uri: http://localhost:9000
          uri: lb://hystrix-consumer
          predicates:
            - Path=/order/**
          # 微服务名称配置
      discovery:
        locator:
          enabled: true # 设置为true 请求路径前可以添加微服务名称
          lower-case-service-id: true # 允许为小写

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka