server:
  port: 8008

spring:
  kafka:
    bootstrap-servers: 192.168.221.129:9092
    producer:
      # 消息发送失败重试次数
      retries: 0
      # 每次批量发送消息的数量
      batch-size: 16384
      # 每次批量发送消息的缓冲区大小
      buffer-memory: 33554432
      # 必须要有分区副本收到消息, 生产者才认为该消息是写入成功的: 0、1、all
      acks: 1
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: test
      # 当各分区下有已提交的offset时, 从提交的offset开始消费, 无提交的offset时, 从头开始消费
      auto-offset-reset: earliest
      enable-auto-commit: true
      auto-commit-interval: 1000
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#    properties:
#      security:
#        protocol: SASL_PLAINTEXT
#      sasl:
#        mechanism: SCRAM-SHA-256
#        jaas:
#          config: 'org.apache.kafka.common.security.scram.ScramLoginModule required username="admin" password="admin-sec";'